"""GU 持久化知识库目录读写（最终产物）。

GU 持久化根 = ``EvolveConfig.get().golden_data_dir / "global_understanding"``。

两种布局（``GUIndex.mode``）：
- **progressive**（skill 多）：``index.md``（frontmatter 索引）+ ``system_wide.md``
  + ``per_skill/<skill>.md`` × N + ``per_skill/__out_of_scope__.md``（越界伪组）。
- **flat**（skill 少）：单 ``global_understanding.md``（整份 GU）+ ``index.md``
  （``mode="flat"``）。

职责边界：本模块**只管最终持久化知识库目录**；builder 的 run workspace 中间结果
（``artifact_dir/gu_<run_id>/``）由 builder 自己用 json/md 写，不经此模块。

骨架阶段：I/O + ``ensure_layout`` + ``route_skill`` 实现到位（可验证）；内容渲染/解析
的语义（md 正文怎么拼）留 TODO 给下一步填 builder 时接上。
"""

from __future__ import annotations

import json
from pathlib import Path

from evo_agent.config import EvolveConfig
from evo_agent.evaluator.domain.models import StandardTrajectory
from evo_agent.evaluator.golden_data.models import GUIndex, GUMode

__all__ = [
    "OUT_OF_SCOPE_SKILL",
    "default_gu_root",
    "ensure_layout",
    "load_index",
    "save_index",
    "load_system_wide",
    "save_system_wide",
    "load_skill_doc",
    "save_skill_doc",
    "load_out_of_scope",
    "save_out_of_scope",
    "load_flat",
    "save_flat",
    "route_skill",
]

# 越界伪组的固定 skill 名（落 per_skill/__out_of_scope__.md）。
OUT_OF_SCOPE_SKILL = "__out_of_scope__"

_INDEX_FILENAME = "index.md"
_SYSTEM_WIDE_FILENAME = "system_wide.md"
_FLAT_FILENAME = "global_understanding.md"
_PER_SKILL_DIR = "per_skill"


# ---------------------------------------------------------------------------
# 路径解析
# ---------------------------------------------------------------------------


def default_gu_root() -> Path:
    """返回 GU 持久化根：``EvolveConfig.get().golden_data_dir / "global_understanding"``。"""
    return EvolveConfig.get().golden_data_dir / "global_understanding"


def _per_skill_path(root: Path, skill: str) -> Path:
    return root / _PER_SKILL_DIR / f"{skill}.md"


def _out_of_scope_path(root: Path) -> Path:
    return _per_skill_path(root, OUT_OF_SCOPE_SKILL)


# ---------------------------------------------------------------------------
# index.md frontmatter 读写（GUIndex <-> md）
# ---------------------------------------------------------------------------


def save_index(root: Path, index: GUIndex) -> Path:
    """把 ``GUIndex`` 写为 ``root/index.md``（YAML frontmatter + 简短正文）。

    frontmatter 手写生成（不依赖 pyyaml）：

    ::

        ---
        mode: progressive
        skills: skill_a, skill_b
        last_run_id: abc123
        out_of_scope_count: 0
        ---
        # Global Understanding Index
        ...
    """
    root.mkdir(parents=True, exist_ok=True)
    path = root / _INDEX_FILENAME
    skills_field = ", ".join(index.skills)
    body = (
        "---\n"
        f"mode: {index.mode}\n"
        f"skills: {skills_field}\n"
        f"last_run_id: {index.last_run_id}\n"
        f"out_of_scope_count: {index.out_of_scope_count}\n"
        "---\n"
        "# Global Understanding Index\n\n"
        f"Auto-generated by golden_data builder. mode={index.mode}, "
        f"skills={len(index.skills)}, last_run_id={index.last_run_id or 'n/a'}.\n"
    )
    path.write_text(body, encoding="utf-8")
    return path


def load_index(root: Path) -> GUIndex:
    """从 ``root/index.md`` 解析 frontmatter 还原 ``GUIndex``；不存在返回默认空索引。

    解析手写 frontmatter（``key: value``，``skills`` 按 ``, `` 分隔）。frontmatter
    缺失或损坏 → 返回默认 ``GUIndex()``（降级，不抛）。
    """
    path = root / _INDEX_FILENAME
    if not path.exists():
        return GUIndex()
    text = path.read_text(encoding="utf-8")
    fields = _parse_frontmatter(text)
    if fields is None:
        return GUIndex()
    skills_raw = fields.get("skills", "")
    skills = [s.strip() for s in skills_raw.split(",") if s.strip()]
    mode_str = fields.get("mode", "progressive")
    mode: GUMode = "flat" if mode_str == "flat" else "progressive"
    try:
        out_of_scope_count = int(fields.get("out_of_scope_count", "0"))
    except ValueError:
        out_of_scope_count = 0
    return GUIndex(
        skills=skills,
        mode=mode,
        last_run_id=fields.get("last_run_id", ""),
        out_of_scope_count=out_of_scope_count,
    )


def _parse_frontmatter(text: str) -> dict[str, str] | None:
    """解析首个 ``---``...``---`` 之间的 ``key: value`` 行为 dict；无 frontmatter 返回 None。"""
    lines = text.splitlines()
    if not lines or lines[0].strip() != "---":
        return None
    fields: dict[str, str] = {}
    for line in lines[1:]:
        if line.strip() == "---":
            return fields
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    return fields  # 未闭合 frontmatter 也返回已收集的字段


# ---------------------------------------------------------------------------
# md 文本载体读写（system_wide / per_skill / out_of_scope / flat）
# ---------------------------------------------------------------------------


def _read_md(path: Path) -> str:
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def _write_md(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path


def load_system_wide(root: Path) -> str:
    return _read_md(root / _SYSTEM_WIDE_FILENAME)


def save_system_wide(root: Path, content: str) -> Path:
    return _write_md(root / _SYSTEM_WIDE_FILENAME, content)


def load_skill_doc(root: Path, skill: str) -> str:
    return _read_md(_per_skill_path(root, skill))


def save_skill_doc(root: Path, skill: str, content: str) -> Path:
    return _write_md(_per_skill_path(root, skill), content)


def load_out_of_scope(root: Path) -> str:
    return _read_md(_out_of_scope_path(root))


def save_out_of_scope(root: Path, content: str) -> Path:
    return _write_md(_out_of_scope_path(root), content)


def load_flat(root: Path) -> str:
    return _read_md(root / _FLAT_FILENAME)


def save_flat(root: Path, content: str) -> Path:
    return _write_md(root / _FLAT_FILENAME, content)


# ---------------------------------------------------------------------------
# 布局初始化
# ---------------------------------------------------------------------------


def ensure_layout(root: Path, mode: GUMode = "progressive") -> Path:
    """按 mode 建空 GU 目录骨架并写初始 ``index.md``（幂等）。

    - progressive：建 ``per_skill/`` 目录，写 ``index.md``（mode=progressive）；
      ``system_wide.md`` 与 per_skill 文件由 builder 填，此处不建空壳。
    - flat：写 ``global_understanding.md`` 空文件占位 + ``index.md``（mode=flat）。
    """
    root.mkdir(parents=True, exist_ok=True)
    if mode == "flat":
        flat_path = root / _FLAT_FILENAME
        if not flat_path.exists():
            flat_path.write_text("", encoding="utf-8")
    else:
        (root / _PER_SKILL_DIR).mkdir(parents=True, exist_ok=True)
    save_index(root, GUIndex(mode=mode))
    return root


# ---------------------------------------------------------------------------
# 渐进式暴露路由
# ---------------------------------------------------------------------------


def route_skill(
    trajectory: StandardTrajectory,
    gu_index: GUIndex,
    attributed_skill: str | None = None,
) -> str | None:
    """按 trace 的 skill 归属信号路由到 GU 的一个 skill 分组（或越界 None）。

    主信号优先序（见记忆 [[expected-behavior-generator-methodology]]）：
    1. ``attributed_skill``（评估器 score.attributed_skill 传入）—— 非空且在
       ``gu_index.skills`` 中则直接返回。
    2. 扫 trajectory 的 message 文本（content + tool_calls 的 name/arguments）里出现的
       skill 名 —— 按长度降序匹配（避免 ``send`` 先于 ``send_email`` 命中），返回首个命中。
    3. 都无 → None（越界，进 ``__out_of_scope__`` 伪组）。

    骨架实现：文本扫描按 skill 名子串匹配。下一步可加 tool_calls read_file 路径、
    adapter skill_list 校验等更稳的归属信号。
    """
    known = [s for s in gu_index.skills if s]
    known_set = set(known)
    if attributed_skill and attributed_skill in known_set:
        return attributed_skill

    blob = _trajectory_text_blob(trajectory)
    if not blob:
        return None
    # 长度降序：长 skill 名先匹配，避免短名子串误命中。
    for skill in sorted(known, key=len, reverse=True):
        if skill in blob:
            return skill
    return None


def _trajectory_text_blob(trajectory: StandardTrajectory) -> str:
    """把 trajectory 的所有 message content + tool_calls 文本拼成一个字符串，供 skill 名扫描。"""
    parts: list[str] = []
    for message in trajectory.messages:
        content = message.content
        if isinstance(content, str):
            parts.append(content)
        elif content is not None:
            parts.append(json.dumps(content, ensure_ascii=False, default=str))
        for tc in message.tool_calls:
            parts.append(json.dumps(tc, ensure_ascii=False, default=str))
    return " ".join(parts)
