server:
  port: 8080

spring:
  application:
    name: versatile-intent
  profiles:
    active: ${PROFILE:layer1}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.openjiuwen: INFO
